// Module included in the following assemblies:
//
// branding-vs-code

[id="defining-custom-branding-values-for-vs-code_{context}"]
= Defining custom branding values for Visual Studio Code - Open Source

This section describes how to customize definitions of basic branding elements of Visual Studio Code.

.Procedure

include::example$snip_{project-context}-link-to-che-code-repository.adoc[]

include::example$snip_{project-context}-step-about-product-json-file.adoc[]
+
TIP: In the `product.json` file, specify all paths relative the `/branding/` folder.
+
.`/branding/product.json`
====
This example shows all of the properties that you can customize:

[source,json,attrs="nowrap",subs="+attributes"]
----
{
    "nameShort": "VS Code - Open Source", # <1>
    "nameLong": "Red Hat OpenShift Dev Spaces with Microsoft Visual Studio Code - Open Source IDE", # <2>
    "icons": {
        "favicon": { # <3>
            "universal": "icons/favicon.ico"
        },
        "welcome": { # <4>
            "universal": "icons/dev-spaces.svg"
        },
        "statusBarItem": { # <5>
            "universal": "icons/dev-spaces.svg"
        },
        "letterpress": { # <6>
            "light": "icons/letterpress-light.svg",
            "dark": "icons/letterpress-light.svg"
        }
    },
    "remoteIndicatorCommands": { # <7>
        "openDocumentationCommand": "Dev Spaces: Open Documentation",
        "openDashboardCommand": "Dev Spaces: Open Dashboard",
        "stopWorkspaceCommand": "Dev Spaces: Stop Workspace"
    },
    "workbenchConfigFilePath": "workbench-config.json", # <8>
    "codiconCssFilePath": "css/codicon.css" # <9>
}
----
<1> The application name for UI elements.
<2> This is used for the *Welcome* page, **About** dialog, and browser tab title.
<3> The icon for the browser tab title for all themes.
<4> The icon for the tab title of the **Get Started** page for all themes.
<5> The icon for the *Product status bar* item for all themes. Define it as `codicon` in the `workbench-config.json` file and the `codicon` CSS styles.
//The second sentence above is not clear to me.
<6> The icon for the empty editor area when all editors are closed. You can provide different icon files for `light` and `dark` themes.
<7> The names of commands provided by the link:https://github.com/che-incubator/che-code/blob/main/code/extensions/che-remote/package.nls.json[Eclipse Che Remote] extension. Users can run these commands by clicking the *Product status bar* item.
//The second sentence above is not clear to me.
<8> The relative path to `workbench-config.json`. See an link:https://github.com/che-incubator/che-code/blob/main/code/src/vs/code/browser/workbench/che/workbench-config.json[example of this file].
<9> The relative path to `css/codicon.css`, which is explained in one of the next steps.
====
+
include::example$snip_{project-context}-admonition-product-json-link.adoc[]

. Add the icon files, which you specified in the `product.json` file in the previous step, to the repository.

include::example$snip_{project-context}-workbench-config-step.adoc[]

include::example$snip_{project-context}-codicon-css-step.adoc[]

. Run the `/branding/branding.sh` script to BUILD? a new container image for Visual Studio Code - Open Source:
+
[subs="+attributes,+quotes"]
----
$ ./branding/branding.sh
----

. Build the container image and push the image to a container registry:
+
[subs="+attributes,+quotes"]
----
$ {docker-cli} build -f build/dockerfiles/linux-musl.Dockerfile -t linux-musl-amd64 .
$ {docker-cli} build -f build/dockerfiles/linux-libc.Dockerfile -t linux-libc-amd64 .
$ export DOCKER_BUILDKIT=1
$ {docker-cli} build -f build/dockerfiles/assembly.Dockerfile -t vs-code-open-source .
$ {docker-cli} push username/vs-code-open-source:next
----
